# Configuration and information used across the site
# Remember: not reloaded automatically when changed.

# Site data
title: Dylan Gattey
email: dylan.gattey@gmail.com
author: dgattey
github:  dgattey
description: "Hello! I'm Dylan. I'm a full-stack software engineer + technical lead working for LinkedIn in San Francisco, passionate about well-designed interfaces and clean code."
logo: favicon-512.png
social:
  links:
    - https://www.linkedin.com/in/dgattey
    - https://github.com/dgattey

# Fonts - if changing these, change the SCSS variables too!!
font_body: Hind:400
font_head: Heebo:700,400
font_url: https://fonts.googleapis.com/css?family=
font_preload_urls: ["https://fonts.gstatic.com", "https://fonts.googleapis.com"]
use_font_loader: false # whether or not to use async JS to load font

# Breakpoints - if changing these, change the SCSS variables too!!
breakpoint_min_tablet: 600px
breakpoint_min_desktop: 900px

# Configuration for site
url: "http://localhost:4000"
permalink: /projects/:title/ #posts
baseurl: ""
google_site_verification: U6mU3aPeTRaCoewYQype946HD1HrM9vY96GoEHKCAnc

# Manifest
lang: en
app_theme_color: 1CD1A5
app_background_color: FFFFFF
app_display: standalone
short_title: dg

# Analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-25241680-2

# Assets
assets:
  gzip: true
  sources:
    - _assets/icons
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"
favicons:
  generic: [32, 57, 76, 96, 128, 196, 228]
  android: [196]
  ios: [120, 152, 180]
  windows: [144]
  thumbnail: [152]

# Workbox settings for Service worker
workbox:
  precache_glob_directory: /
  precache_glob_patterns:
    - "assets/*.{js,css,svg,json}"
    - "assets/favicon*"
    - index.html
    - "/404/*"
    - "/offline/*"
    - "favicon*"
  precache_recent_posts_num: 5
  precache_glob_ignores: []

# Sitemap config - excludes google analytics html file
defaults:
  -
    scope:
      path: "google*.html"
    values:
      sitemap:  false

# Build settings
markdown: kramdown
source: src
destination: build
include: [static, .htaccess]
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style:  expanded
  deploy_style: compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-seo-tag
  - jekyll-assets
  - jekyll-workbox-plugin
  - autoprefixer-rails
