# Configuration and information used across the site
# Remember: not reloaded automatically when changed.

# Site data
title: Dylan Gattey
email: dylan.gattey@gmail.com
description: >
    I'm a software developer @ LinkedIn + amateur designer 
    based out of San Francisco, passionate about making 
    things look nice, crafting clean interfaces, and 
    architecting efficient code. When not working, I run 
    through the hills of SF and find farmer's markets so I
    can cook delicious food.
twitter: dgattey
github:  dgattey

# Configuration for site
url: "https://dylangattey.com"
permalink: /projects/:year/:title/ #posts
baseurl: ""

# Build settings
markdown: kramdown
source: dg
destination: build
