# Configuration and information used across the site
# Remember: not reloaded automatically when changed.

# Site data
title: Dylan Gattey
email: dylan.gattey@gmail.com
twitter: dgattey
github:  dgattey

# Configuration for site
url: "https://dylangattey.com"
permalink: /projects/:title/ #posts
baseurl: ""
filter_tags:
  - ios
  - web

# Build settings
markdown: kramdown
source: dg
destination: build
sass:
  style:  expanded
  deploy_style: compressed