# Configuration and information used across the site
# Remember: not reloaded automatically when changed.

# Site data
title: Dylan Gattey
email: dylan.gattey@gmail.com
author: dgattey
github:  dgattey
description: "Hello! I'm Dylan. I'm a full-stack software engineer + technical lead working for LinkedIn in San Francisco, passionate about well-designed interfaces and clean code."
logo: /img/logo-512x512.png
social:
  links:
    - https://www.linkedin.com/in/dgattey
    - https://github.com/dgattey

# Configuration for site
url: "https://dylangattey.com"
permalink: /projects/:title/ #posts
baseurl: ""
google_site_verification: U6mU3aPeTRaCoewYQype946HD1HrM9vY96GoEHKCAnc

# Manifest
lang: en
app_theme_color: 1CD1A5
app_background_color: FFFFFF
app_display: standalone
short_title: dg

# Analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-25241680-2

# Assets
assets:
  autoprefixer:
    browsers:
    - "last 2 versions"
    - "IE > 9"

# Sitemap config - excludes google analytics html file
defaults:
  -
    scope:
      path: "google*.html"
    values:
      sitemap:  false

# Build settings
markdown: kramdown
source: dg
destination: build
include: [static]
sass:
  style:  expanded
  deploy_style: compressed

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-seo-tag
  - jekyll-assets
  - autoprefixer-rails