# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dylan Gattey
email: dylan.gattey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    The portfolio site of a coder/designer based out of San Francisco.
    I make things look nice. I also write words on screens so you 
    can use that hunk of metal in your pocket. Current property of 
    Brown University. When not coding or designing, I run so I can cook 
    way too much good food.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dylangattey.com" # the base hostname & protocol for your site
twitter_username: dgattey
github_username:  dgattey

# Build settings
markdown: kramdown
source: dg
destination: build
incremental: true
markdown: kramdownm
